NUOVO/Controllers/ClientiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NUOVO.DAL;
using NUOVO.Models;

namespace NUOVO.Controllers
{
    [Authorize]
    public class ClientiController : Controller 
    {
        private Context db = new Context();

        // GET: Clienti
        public ActionResult Index()
        {
            return View(db.Cliente.ToList());
        }

        // GET: Clienti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clienti/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clienti/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClienteID,RagioneSociale,Telefono,Mail")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clienti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clienti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClienteID,RagioneSociale,Telefono,Mail")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Clienti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clienti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NUOVO/Controllers/CommessaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NUOVO.DAL;
using NUOVO.Models;
using System.Globalization;
using System.Threading;

namespace NUOVO.Controllers
{
    [Authorize]

   
    public class CommessaController : Controller
    {

        private Context db = new Context();

        // GET: Commessa
        public ActionResult Index()
        {
            var commessa = db.Commessa.Include(c => c.Cliente);
            return View(commessa.ToList());
        }

        // GET: Commessa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commessa commessa = db.Commessa.Find(id);
            if (commessa == null)
            {
                return HttpNotFound();
            }
            return View(commessa);
        }

        // GET: Commessa/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.Cliente, "ClienteID", "RagioneSociale");
            return View();
        }

        // POST: Commessa/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommessaID,Descrizione,ClienteID,DataInizio,DataFine,Importo")] Commessa commessa)
        {

            if (ModelState.IsValid)
            {
                db.Commessa.Add(commessa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.Cliente, "ClienteID", "RagioneSociale", commessa.ClienteID);
            return View(commessa);
        }

        // GET: Commessa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commessa commessa = db.Commessa.Find(id);
            if (commessa == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.Cliente, "ClienteID", "RagioneSociale", commessa.ClienteID);
            return View(commessa);
        }

        // POST: Commessa/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommessaID,Descrizione,ClienteID,DataInizio,DataFine,Importo")] Commessa commessa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commessa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteID = new SelectList(db.Cliente, "ClienteID", "RagioneSociale", commessa.ClienteID);
            return View(commessa);
        }

        // GET: Commessa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commessa commessa = db.Commessa.Find(id);
            if (commessa == null)
            {
                return HttpNotFound();
            }
            return View(commessa);
        }

        // POST: Commessa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Commessa commessa = db.Commessa.Find(id);
            db.Commessa.Remove(commessa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public JsonResult SetDataOdierna()
        {
            //Commessa commessa = db.Commessa.Where(q => q.CommessaID == CommessaID).FirstOrDefault();
            int giorno = DateTime.Now.Day;
            int mese = DateTime.Now.Month;
            int anno = DateTime.Now.Year;

            return Json(new { giorno, mese, anno });
        }


        [HttpPost]
        public JsonResult SetInizio(int CommessaID)
        {
            Commessa commessa = db.Commessa.Where(q => q.CommessaID == CommessaID)
                .FirstOrDefault();
            string giornoR = commessa.DataInizio.Day.ToString();
            string meseR = commessa.DataInizio.Month.ToString();
            string annoR = commessa.DataInizio.Year.ToString();

            if (commessa.DataInizio.Month < 10)
            {
                meseR = "0" + meseR;
            }

            if (commessa.DataInizio.Day < 10)
            {
                giornoR = "0" + giornoR;
            }

            return Json(new { giornoR, meseR, annoR });
        }
    }
}

NUOVO/Controllers/StackholderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NUOVO.DAL;
using NUOVO.Models;

namespace NUOVO.Controllers
{
    [Authorize]
    public class StackholderController : Controller
    {
        private Context db = new Context();

        // GET: Stackholder
        public ActionResult Index()
        {
            return View(db.Stackholder.ToList());
        }

        // GET: Stackholder/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stackholder stackholder = db.Stackholder.Find(id);
            if (stackholder == null)
            {
                return HttpNotFound();
            }
            return View(stackholder);
        }

        // GET: Stackholder/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stackholder/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StackholderID,Nome,Cognome,Telefono,Cellulare,Mail,Note")] Stackholder stackholder)
        {
            if (ModelState.IsValid)
            {
                db.Stackholder.Add(stackholder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stackholder);
        }

        // GET: Stackholder/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stackholder stackholder = db.Stackholder.Find(id);
            if (stackholder == null)
            {
                return HttpNotFound();
            }
            return View(stackholder);
        }

        // POST: Stackholder/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StackholderID,Nome,Cognome,Telefono,Cellulare,Mail,Note")] Stackholder stackholder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stackholder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stackholder);
        }

        // GET: Stackholder/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stackholder stackholder = db.Stackholder.Find(id);
            if (stackholder == null)
            {
                return HttpNotFound();
            }
            return View(stackholder);
        }

        // POST: Stackholder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stackholder stackholder = db.Stackholder.Find(id);
            db.Stackholder.Remove(stackholder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NUOVO/Views/Shared/_Layout.cshtml
@*@model IEnumerable<PROGETTO.Models.Cliente>

@{ 
    ViewBag.Title = "Index";
}*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Prova</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/Content/Site.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using Microsoft.AspNet.Identity
</head>
<body>

    <div class="page dashboard">
        <div class="leftMenu">
            <div class="menu">
                @Html.Partial("_LoginPartial")
                @*@Html.ActionLink("Reset Password","ResetPassword", "Account")*@
                <ul class="vociMenu">
                    <li>
                        <div class="inline">
                            <span class="voce"> @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</span>
                        </div>
                    </li>
                    <li>
                        <div class="inline">
                            <span class="voce"> @Html.ActionLink("Gestione Clienti", "Index", "Clienti") </span>
                        </div>
                    </li>
                    <li class="campiFormazione">
                        <div class="inline">
                            <span class="voce">@Html.ActionLink("Gestione Commesse", "Index", "Commessa")</span>
                        </div>
                    </li>
                    <li class="campiFormazione">
                        <div class="inline">
                            <span class="voce">@Html.ActionLink("Gestione Stackholders", "Index", "Stackholder")</span>
                        </div>
                    </li>
                    <li class="campiFormazione">
                        <div class="inline">
                            <span class="voce">@Html.ActionLink("Gestione Rilevamenti", "Index", "CommessaStackholder")</span>
                        </div>
                    </li>
                    <li class="campiFormazione">
                        <div class="inline">
                            <span class="voce">@Html.ActionLink("Gestione Rischi", "Index", "CommessaRischio")</span>
                        </div>
                    </li>
                </ul>

            </div>
        </div>
        <div class="pageBody">
            <div class="container">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Entity & Identity Framework</p>
                </footer>
            </div>
        </div>

    </div>



    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @section Scripts {


        <script src="~/Scripts/globalize/globalize.js"></script>
        <script src="~/Scripts/globalize/cultures/globalize.culture.@(System.Threading.Thread.CurrentThread.CurrentCulture.Name).js"></script>
        <script>
    //$.validator.methods.number = function (value, element) {
    //    return this.optional(element) ||
    //        !isNaN(Globalize.parseFloat(value));
    //}
    $(document).ready(function () {
        Globalize.culture('@(System.Threading.Thread.CurrentThread.CurrentCulture.Name)');
    });
        </script>
        <script>
            //jQuery.extend(jQuery.validator.methods, {
            //    range: function (value, element, param) {
            //        //Use the Globalization plugin to parse the value
            //        var val = Globalize.parseFloat(value);
            //        return this.optional(element) || (
            //            val >= param[0] && val <= param[1]);
            //    }
            //});
            $.validator.methods.date = function (value, element) {
                return this.optional(element) ||
                    Globalize.parseDate(value) ||
                    Globalize.parseDate(value, "yyyy-MM-dd");
            }
        </script>

        <script src="~/Scripts/globalize/globalize.js"></script>
        @*<script src="~/Scripts/globalize/cultures/globalize.culture.@(System.Threading.Thread.CurrentThread.CurrentCulture.GetCultureInfo("en-US")).js"></script>*@
        <script>
    $.validator.methods.number = function (value, element) {
        return this.optional(element) ||
            !isNaN(Globalize.parseFloat(value));
    }
    $(document).ready(function () {
        Globalize.culture('@(System.Threading.Thread.CurrentThread.CurrentCulture.Name)');
    });
        </script>
        <script>
            //jQuery.extend(jQuery.validator.methods, {
            //    range: function (value, element, param) {
            //        //Use the Globalization plugin to parse the value
            //        var val = Globalize.parseFloat(value);
            //        return this.optional(element) || (
            //            val >= param[0] && val <= param[1]);
            //    }
            //});
            $.validator.methods.date = function (value, element) {
                return this.optional(element) ||
                    Globalize.parseDate(value) ||
                    Globalize.parseDate(value, "yyyy-MM-dd");
            }
        </script>
    }
    

</body>
</html>